### PR TITLE
login repo and view model

### PR DESCRIPTION
**Pull request by andrew-pogue**
the per-table repos still need work but the login one works

### CODE REVIEW

**Review by emptyloot — DISMISSED** [review]
I have looked over every file. I see the start of refactoring of code. I agree with a lot of the code movement and I like the name changes.  I am also refactoring code right now. I think this is great and will help me with what I am working on.   I also see a lot of extra code for SessionRepository and LoginRepository. I am not sure how you will use SessionRepository. I feel like a lot of the code is extra for the file but could be moved and will still be used. I think we should merge this after our meeting tomorrow. That could also give someone else time to look it over.

**Comment by andrew-pogue** [comment]
@emptyloot Thank you for your feedback. Session repo is not being used for anything yet. Session repository was my first approach to creating a repo that you can login and logout with. It was supposed to encapsulate AWS Cognito and Auth User Pools. Its implemented via call-backs which you said you preferred. I tried using the session repository in the login view-model but I was getting fatal java runtime errors (something about writing to memory i shouldn't be). So, I removed all calls to session repository and replaced it with login repository, which is implemented via kotlin coroutines and things just worked. I kept session repository around because I was thinking about converting it to a user repository. You talked earlier about removing the user table from the database and using cognito user pools instead, the code in session repo gets user data from cognito.

**Review by emptyloot — COMMENTED** [review]
I think the login view model became more complicated. The state of the login screen, user email and password, should be stored on the view model like it was before. This makes the login function from the view model more simple. For example you would not need to pass in the email to the login function from the view model because it is already stored in the view model. You would need to pass the email and password to the repository.  Try having the repository give the view model on success or on failure result. Then read the result in the view model and handle the logic there. I have pushed my latest branch I am working on. My main menu screen view model navigates and handles the logic. I think this will keep the logic and state isolated to the view model.  Take a look here https://github.com/BC-CS481-Capstone/ReturnPalsApp/blob/6a53ee2bc61a367946a5c3229fef17451e204446/app/src/main/java/com/example/returnpals/composetools/mainMenu/MainMenuScreen.kt

**Comment by andrew-pogue** [comment]
I think we have differing ideals here. The view model only needs to store state that needs to be shared with multiple screens. UI state that is specific to one screen and no other screen can be stored within the composable itself. The first view model we developed was the pickup view model and the only reason we transitioned in that direction was because we needed to somehow share data between screens. The password shouldn't be known outside of the login screen and the username is the username specific to the text field on the login screen.

Also, I spent a lot of time (20+ hours or something) trying to get the coroutines to work for the login view model and login repository, and I think they work well, and I don't want to just dump all the work I did on this already working repository. I don't mind if other repositories are implemented via callbacks.

**Review by emptyloot — APPROVED** [review]
Thanks

**Pull request merged**
